import {
  BedDouble,
  Building,
  Flower2,
  Gem,
  House,
  Landmark,
  MapPin,
  Mountain,
  MountainSnow,
  Music,
  Plane,
  PlaneTakeoff,
  Sailboat,
  Sun,
  TrainFront,
  TreePalm,
  Trees,
  UtensilsCrossed,
  WavesHorizontal,
  type LucideIcon,
} from "lucide-react";
import type { JourneyStopKind } from "@/lib/types";

export const STOP_ICON: Record<JourneyStopKind, LucideIcon> = {
  home: House,
  flight: Plane,
  train: TrainFront,
  arrival: MapPin,
  hotel: BedDouble,
  airport: PlaneTakeoff,
  beach: TreePalm,
  water: WavesHorizontal,
  island: Sailboat,
  culture: Landmark,
  food: UtensilsCrossed,
  nature: Trees,
  adventure: Mountain,
  nightlife: Music,
  wellness: Flower2,
  luxury: Gem,
  city: Building,
  desert: Sun,
  mountain: MountainSnow,
};
